apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqd-client-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mqd-client
          image: shippozudo/pocmqd:latest
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_URL
              value: "http://proxy-service:8081"
            - name: CONFIG_URL
              value: "http://mqd-client-service:8080/settings/configurationSettings.json"
          volumeMounts:
            - name: ssl-certs
              mountPath: /certificates
      volumes:
        - name: ssl-certs
          secret:
            secretName: ssl-certs-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: proxy
          image: nginx:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: ssl-certs
          secret:
            secretName: ssl-certs-secret
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort