apiVersion: v1
kind: ConfigMap
metadata:
  name: mqd-client-config
data:
  API_PORT: ":8080"
  SERVER_ORG_ID: "09b20d09-bf30-4497-938e-b0ead8ce9629"
  ENVIRONMENT: "DEV"
  LOGGING_LEVEL: "WARNING"
  APPLICATION_MODE: "TRANSMITTER"
  PROXY_URL: "http://proxy:80"
  CLIENT_CRT_FILE: "client.crt"
  CLIENT_KEY_FILE: "client.key"