version: '3'
services:
  mqd-client:
    image: mqd-client:latest
    ports:
      - "8080:8080"
    environment:
      - API_PORT=:8080
      - SERVER_ORG_ID=09b20d09-bf30-4497-938e-b0ead8ce9629
      - REPORT_EXECUTION_WINDOW=5
      - ENVIRONMENT=SANDBOX
      - LOGGING_LEVEL=DEBUG
      - APPLICATION_MODE=TRANSMITTER
      - PROXY_URL=http://192.168.59.100:8081
      - ENABLE_HTTPS=FALSE
      - RESULT_ENABLED=FALSE
      - RESULT_FILES_PER_DAY=8
      - RESULT_DAYS_TO_STORE=3
      - RESULT_SAMPLES_PER_ERROR=5
      - RESULT_MASK_PRIVATE_CONTENT=TRUE
    volumes:
      - ./certificates:/certificates/
      - ./settings:/settings/
      - ./data_logs:/data_logs/
    network_mode: "host"
    depends_on:
      - proxy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M
  proxy:
    image: nginx
    ports:
      - "8081:80"
    volumes:
     - ./proxy/default.sandbox.conf:/etc/nginx/conf.d/default.conf:ro
     - ./certificates:/etc/ssl