version: '3'
services:
  mqd-client:
    image: mqd-client:latest
    ports:
      - "8080:8080"
    environment:
      - API_PORT=:8080
      - SERVER_ORG_ID=09b20d09-bf30-4497-938e-b0ead8ce9629
      - PROXY_URL=http://192.168.59.100:8081
    volumes:
      - ./certificates:/certificates/
    network_mode: "host"
    depends_on:
      - proxy

  proxy:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./proxy/default.sandbox.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificates:/etc/ssl