version: '3'
services:
  mqd-client:
    image: shippozudo/pocmqd:latest
    ports:
      - "8080:8080"
    environment:
      - API_PORT=:8080
      - SERVER_ORG_ID=09b20d09-bf30-4497-938e-b0ead8ce9629
      - ENVIRONMENT=DEV
      - LOGGING_LEVEL=WARNING
      - APPLICATION_MODE=TRANSMITTER
      - PROXY_URL=http://proxy:8081
    volumes:
      - ./certificates:/certificates/
    network_mode: "host"
    depends_on:
      - proxy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M
  proxy:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./proxy/default.sandbox.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificates:/etc/ssl