services:
  mqd-client:
    image: mqd-client:latest
    ports:
      - "8080:8080"
    environment:
      - API_PORT=:8080
      - SERVER_ORG_ID=09b20d09-bf30-4497-938e-b0ead8ce9629
      - REPORT_EXECUTION_WINDOW=5
      - ENVIRONMENT=DEV
      - LOGGING_LEVEL=DEBUG
      - APPLICATION_MODE=TRANSMITTER
      - PROXY_URL=http://172.18.0.2:80 # Use o nome do serviço "proxy"
      - ENABLE_HTTPS=FALSE
      - RESULT_ENABLED=FALSE
      - RESULT_FILES_PER_DAY=8
      - RESULT_DAYS_TO_STORE=3
      - RESULT_SAMPLES_PER_ERROR=5
      - RESULT_MASK_PRIVATE_CONTENT=TRUE
    volumes:
      - ./Certificates:/certificates/  # Caminho corrigido
      - ./settings:/settings/
      - ./data_logs:/data_logs/
      - ./settings/configurationSettings.json:/etc/nginx/settings/configurationSettings.json
    depends_on:
      - proxy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M

  proxy:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./Proxy/default.sandbox.conf:/etc/nginx/conf.d/default.conf  # Caminho corrigido
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf  # Caminho corrigido
      - ./Certificates:/etc/ssl  # Caminho corrigido