apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://mqd-client:8080;
        }
    }
        
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/ssl/client.crt;
        ssl_certificate_key /etc/ssl/client.key;

        location / {
            proxy_pass http://mqd-client:8080;
        }
    }