apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 8081;
            server_name localhost;

            location /settings {
                proxy_pass http://mqd-client-service:8080/settings/configurationSettings.json;
            }

            location /ValidateResponse {
                proxy_pass http://mqd-client-service:8080/ValidateResponse;
            }
        }
    }