apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqd-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqd-client
  template:
    metadata:
      labels:
        app: mqd-client
    spec:
      containers:
        - name: mqd-client
          image: shippozudo/pocmqd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_URL
              value: "http://proxy-service:8082"
            - name: API_PORT
              value: ":8080"
            - name: SERVER_ORG_ID
              value: "09b20d09-bf30-4497-938e-b0ead8ce9629"
            - name: ENVIRONMENT
              value: "DEV"
            - name: LOGGING_LEVEL
              value: "WARNING"
            - name: APPLICATION_MODE
              value: "TRANSMITTER"
            - name: ENABLE_HTTPS
              value: "TRUE"
            - name: CERTIFICATE_PATH
              value: "/certificates"
          volumeMounts:
            - name: ssl-certs
              mountPath: /certificates  # Montando os certificados SSL no contêiner
      volumes:
        - name: ssl-certs
          secret:
            secretName: ssl-certs-secret   # Referência ao Secret que contém os certificados SSL
---
apiVersion: v1
kind: Service
metadata:
  name: mqd-client-service
spec:
  selector:
    app: mqd-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: nginx:latest
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl  # Mapeando os certificados SSL para o caminho correto no proxy
      volumes:
        - name: ssl-certs
          secret:
            secretName: ssl-certs-secret
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
