name: Build and Push Docker Image OPFinance MQD

on:
  push:
    branches:
      - main  # Aciona o workflow quando há push na branch 'main'
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Usando a imagem do Ubuntu para rodar o build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Faz o checkout do código do repositório

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -f infra/dockerfile/dockerfile-minimal -t shippozudo/pocmqd:latest .  # Caminho correto para o Dockerfile

      - name: Push da imagem Docker para o Docker Hub
        run: docker push shippozudo/pocmqd:latest  # Push da imagem para o Docker Hub
